#!/usr/bin/env bash

SCREENSHOT=$(mktemp --suffix ".png")
LOCKIMG="~/.config/i3/img/lock.png"
if scrot -zo "${SCREENSHOT}" && magick "${SCREENSHOT}" -blur "0x8" -modulate 75 "${SCREENSHOT}"; then
    i3lock --image "${SCREENSHOT}" "$@"
else
    if [[ -f "${LOCKIMG}" ]]; then
        i3lock --tiling --image "${LOCKIMG}" "$@"
    else
        i3lock --color=303030 "$@"
    fi
fi
rm -f "${SCREENSHOT}"
